name: Build on Debian

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  cmake-build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Debian software sources
      run: |
        echo "deb http://deb.debian.org/debian/ bullseye main" | tee /etc/apt/sources.list
        echo "deb http://deb.debian.org/debian/ bullseye-updates main" | tee -a /etc/apt/sources.list
        echo "deb http://security.debian.org/ bullseye-security main" | tee -a /etc/apt/sources.list
        echo "deb http://deb.debian.org/debian unstable main" | tee -a /etc/apt/sources.list

    - name: Install Build Requirements
      run: |
        apt-get update -q
        apt install -y g++ cmake extra-cmake-modules qt6-declarative-dev qt6-declarative-private-dev qt6-base-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
